# Generated by Django 3.1.5 on 2021-01-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Death Date'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(
                      blank=True, 
                      choices=[
                          ('m', 'Maintenance'),
                          ('o', 'On loan'),
                          ('a', 'Available'),
                          ('r', 'Reserved')
                      ],
                      default='d', 
                      help_text='Book availability', 
                      max_length=1
                  ),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text="Enter the book's natural language (e.g. English (South Africa), Tswana, Zulu etc.)", max_length=200),
        ),
    ]
